title: Warren Jacinto Blog
description: Warren Jacinto aka DeadSpheroid's blog for all things code

url: https://deadspheroid.github.io/my-blog
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: /my-blog
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
future: true

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    github: deadspheroid
    email: warrenjacinto@gmail.com
    linkedin: warren-jacinto


google_analytics: "UA-58263416-1"

